### PR TITLE
Support new flattened data format, var domains, and chunking example

### LINKED ISSUE #37: Sparse domain support for categorical vars
The sparse domain implementation in DW isn't particularly efficient, but it's used in many apps. Do we have a plan to support that soon (so we can test on a wider range of DD apps)? If no one has started working on it, I'd be happy to take the first stab.

### PR DESCRIPTION
**Pull request by alldefector**
Fixes #37

On the chunking example (2K + 2K), NS is about 16 sec / learning epoch (DW is 0.4 sec):
```
2016-09-04 10:40:01.088866 + numbskull flat --output_dir weights --threads 3 -l 100 -i 100 --sample_evidence
2016-09-04 10:40:24.930151 Meta:
2016-09-04 10:40:24.930206     weights:   243980
2016-09-04 10:40:24.930228     variables: 3838
2016-09-04 10:40:24.930245     factors:   7913972
2016-09-04 10:40:24.930261     edges:     11471372
2016-09-04 10:40:24.930278 
2016-09-04 10:40:24.930295 DONE WITH WEIGHTS
2016-09-04 10:40:24.930310 DONE WITH VARS
2016-09-04 10:40:24.930326 DONE WITH FACTORS
2016-09-04 10:40:24.930343 FACTOR 0: STARTED LEARNING
2016-09-04 10:40:24.930361 FACTOR 0: EPOCH #0
2016-09-04 10:40:24.930379 Current stepsize = 0.0095
2016-09-04 10:40:40.512336 FACTOR 0: EPOCH #1
2016-09-04 10:40:40.512406 Current stepsize = 0.009025
2016-09-04 10:40:56.147489 FACTOR 0: EPOCH #2
2016-09-04 10:40:56.147546 Current stepsize = 0.00857375
2016-09-04 10:41:11.845506 FACTOR 0: EPOCH #3
2016-09-04 10:41:11.845568 Current stepsize = 0.0081450625
```

### CODE REVIEW

**Comment by alldefector** [comment]
To recap, NS seems to be 40X slower than DW on chunking. We should profile that and see if we can reduce the gap...

@bryan-he fysa, I'm working on the (sparse) domain mapping next in the same branch. Should be ready tonight or tomorrow. After that, NS should be able to run all DD apps.

**Comment by alldefector** [comment]
Last commit was a big and tough one. Some highlights ( @bryan-he @thodrek please review ):
- Fixed apparent bug with multi threads sharing same temp var `Z`. Now using copies. (Without this fix, the weights look extreme.)
- Updated `reg_param` to default to 0.01 to be consistent with DW.
- Using same 2-tier var-to-factor indexing structure as latest DW.
- Chunking speed is now about 1.5 sec / learning epoch!!! Attributable to the new indexing structure because it filters by value. Now it's only a `4X` difference from DW. Inference is 0.75 sec / epoch, `2X` as slow as DW. Weights and probabilities all look very close to DW with eyeballing.
- Changed SGD routine to use two assignment arrays (`var_values_evid` in addition to `var_values`) to be consistent with DW. (Did this while trying to make learning work.)
- Kept `nopython` on all routines after much struggling with domain mapping. Eventually used `bisect` (aka `searchsorted`) in numpy (as opposed to `dict`) to keep `nopython` possible.
- Supports `sample_evidence` now.
- You may need to update `numba` to 0.28 if your version is older.
- Made data structure a bit more "wasteful" to be consistent with DW.

I'm yet to test it on a really sparse domain program, but given its support for census and chunking, I think we can declare preliminary feature parity with DW now!

**Comment by thodrek** [comment]
This sounds awesome! I’ll do a code review :)
Do you want to sync up as well for the distributed version?
Suggested to Bryan to use 0MQ but other suggestions are
more than welcome :)

On Sep 5, 2016, at 9:52 PM, alldefector <notifications@github.com<mailto:notifications@github.com>> wrote:


Last commit was a big and tough one. Some highlights ( @bryan-he<https://github.com/bryan-he> @thodrek<https://github.com/thodrek> please review ):

  *   Fixed apparent bug with multi threads sharing same temp var Z. Now using copies. (Without this fix, the weights look extreme.)
  *   Updated reg_param to default to 0.01 to be consistent with DW.
  *   Using same 2-tier var-to-factor indexing structure as latest DW.
  *   Chunking speed is now about 1.5 sec / learning epoch!!! Attributable to the new indexing structure because it filters by value. Now it's only a 4X difference from DW. Inference is 0.75 sec / epoch, 2X as slow as DW. Weights and probabilities all look very close to DW with eyeballing.
  *   Changed SGD routine to use two assignment arrays (var_values_evid in addition to var_values) to be consistent with DW. (Did this while trying to make learning work.)
  *   Kept nopython on all routines after much struggling with domain mapping. Eventually used bisect (aka searchsorted) in numpy (as opposed to dict) to keep nopython possible.
  *   Supports sample_evidence now.
  *   You may need to update numba to 0.28 if your version is older.
  *   Made data structure a bit more "wasteful" to be consistent with DW.

I'm yet to test it on a really sparse domain program, but given its support for census and chunking, I think we can declare preliminary feature parity with DW now!

**Comment by alldefector** [comment]
A few more data points on an MEMEX NER app (memex1 in https://github.com/HazyResearch/sampler/pull/53, thanks to @xiaoling ):

```
09/08/2016 12:03:54 AM 2016-09-08 00:03:54.716744 + numbskull flat --output_dir weights --threads 31 -l
 500 -i 200 -s 0.1 --sample_evidence
09/08/2016 12:04:02 AM 2016-09-08 00:04:02.062491 Meta:
09/08/2016 12:04:02 AM 2016-09-08 00:04:02.062717     weights:   6708008
09/08/2016 12:04:02 AM 2016-09-08 00:04:02.062740     variables: 10549449
09/08/2016 12:04:02 AM 2016-09-08 00:04:02.062756     factors:   392383012
09/08/2016 12:04:02 AM 2016-09-08 00:04:02.062771     edges:     438845368
09/08/2016 12:04:02 AM 2016-09-08 00:04:02.062785
09/08/2016 12:04:02 AM 2016-09-08 00:04:02.062800 LOADED WEIGHTS
09/08/2016 12:04:02 AM 2016-09-08 00:04:02.062814 LOADED VARS
09/08/2016 12:04:35 AM 2016-09-08 00:04:35.379908 #VTF = 21098898
```

- memory: 24 gb at its peak (32 gb with DW)
- factor graph loading : ~6 mins
- each learning epoch takes around 8 seconds and each inference epoch takes 5 seconds (vs 4.2 and 3.6 using deepdive-flatten)

Output weights and probs are very close to DW.

So, NS uses 25% less memory and is no more than 2X slower than DW. Pretty competitive!

**Comment by chrismre** [comment]
AWESOME! Thanks for the benchmarking. Exciting to get this thing running!!

**Comment by thodrek** [comment]
Thanks for this Feng !! This is great news!



On Sep 8, 2016, at 11:19 AM, chrismre <notifications@github.com<mailto:notifications@github.com>> wrote:

AWESOME! Thanks for the benchmarking. Exciting to get this thing running!!

**Comment by bryan-he** [comment]
NS can actually be sped up by a factor of ~1.5--2 by manually inlining functions calls.

Numba/Python doesn't know how to do this automatically, and the code becomes really difficult to read, so it isn't done right now.

**Pull request merged**
